### ISSUE TITLE
[RFE] Can not provide the openstack AZ

### ISSUE THREAD

**Issue by hchenxa** [openshift/installer#2391]
# Version

```

$ openshift-install version
./openshift-install v4.2.0
built from commit 1358b443329caffc2207aebafb798d12c10fc169
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:9e56302745c01950bbb3750d8fd744b64d4cd1da985dab6a92c1e98f1779d241

```

# Platform:

Openstack

# What happened?

I can not provide the AZ for OCP installation on Openstack, refer https://github.com/openshift/installer/blob/master/pkg/asset/machines/openstack/machinesets.go#L34-L36, so any plan to support availableZone on Openstack?

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

I want to define the AZ in install-config.yaml so that I can control the machine in AZ when deploy the openshift.

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

**Comment by alaindfisher** [comment]
I have also hit this issue as we have multiple AZ's in our environment so will be interested in a response.

**Comment by MartijnStraatman** [comment]
Yes, please add this feature. With openshift 3.11 we divide the masters and workers across our available az's

**Comment by rvanbutselaar** [comment]
Please add this feature. We would like to divide the master/worker nodes across multiple AZ's.

**Comment by tomassedovic** [comment]
We do plan to add AZ support. I can't promise exactly when, but it will likely be in the next couple of months.

**Comment by hchenxa** [comment]
@rvanbutselaar @tomassedovic any good news?

**Comment by klaphi** [comment]
I can confirm that this is an "urgent" issue. 

I have used the latest 4.4 installer which results in the following openshift deployment on RedHat Openstack 13.

```
$ ./openshift-install version
./openshift-install v4.4.0
built from commit fc601b95bc0fdda092c8b3b7eb4849590e87d415
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:e1dab3d24a8c2f1b8f4e7d4b1a2f3db80e30e914bf4f2aed2caf260d25df8944


$ openstack --os-cloud openstack server list --long -c "Availability Zone"  -c Name
+-------------------------+-------------------+
| Name                    | Availability Zone |
+-------------------------+-------------------+
| ocp4-5pk4t-worker-rj5f9 | KRL_AZ3           |
| ocp4-5pk4t-worker-tm2z5 | KRL_AZ3           |
| ocp4-5pk4t-worker-gbw6n | KRL_AZ3           |
| ocp4-5pk4t-master-2     | KRL_AZ4           |
| ocp4-5pk4t-master-0     | KRL_AZ4           |
| ocp4-5pk4t-master-1     | KRL_AZ4           |
+-------------------------+-------------------+

```
In case of failing AZ we will have a control plane or worker nodes but not both.  

In Openstack you can use Regions but you dont have to. We have only one Region with several AZs.

**Comment by pierreprinetti** [comment]
OpenStack AZs are not supported as of OpenShift 4.4; however, we plan to add them soon and possibly in 4.5

**Comment by ITD27M01** [comment]
Hi Guys. I have created patchsets for release 4.3: https://github.com/ITD27M01/openshift-installer-patchset for real OpenStack installations.
The most useful one is OpenStack availability zone support (for installer and CRDs too). Also taken into account the necessity to specify AZ for network and router.

**Comment by ITD27M01** [comment]
@klaphi 
BTW, currently you can create extra machineset for workers and specify the availabilityZone parameter:
``` 
kubectl get machineset/cluster-rx27d-worker -n openshift-machine-api -o yaml
<...>
      providerSpec:
        value:
          apiVersion: openstackproviderconfig.openshift.io/v1alpha1
          availabilityZone: az-rtc-cloud
          cloudName: openstack
<...>
```

**Comment by klaphi** [comment]
Hi guys, do you know when this feature will be implemented ? We have an urgent need for that and yes I can patch the installer but otherwise we spent a lot of money for licenses to get supported software.

**Comment by ITD27M01** [comment]
@klaphi 

I am in the same position as you and expect a change from RedHat. Based on the installer's code repository - while other infrastructures are less of a priority for product owners, high priority is given to development for the AWS public cloud and on-promise VMWare installations. I would suggest you create a case on RedHat technical support, as I did, and escalate it. I will also escalate my case. This will carry the attention of managers and increase the priority of this task.

In the first iteration of the escalation, they will ask you to use the UPI scenario for 4.4 release, but this is a complex way with many manual actions. There we need to provide good reasons for using the installer instead of UPI.

We are using installer currently to provide on-demand OpenShift clusters for internal developers (tests and devs), and it is our business requirements.

**Comment by jichenjc** [comment]
yes, we have same requirement on this ... +1 to all above

**Comment by mandre** [comment]
/close
We've implemented support for AZs with https://github.com/openshift/installer/pull/3918, to be available in version 4.6.

**Comment by ITD27M01** [comment]
@mandre @iamemilio 
Hi, I cannot agree with solution provided because it is partially implemented. As for AWS there should be AZ management for networks and volumes. The virtual machine provisioning will fail because volumes cannot be attached from another (different than OpenStack instance) AZ as well as network agents cannot spawn networks/ports and, more importantly, L3 Router from another AZ.

**Comment by klaphi** [comment]
> @mandre @iamemilio
> Hi, I cannot agree with solution provided because it is partially implemented. As for AWS there should be AZ management for networks and volumes. The virtual machine provisioning will fail because volumes cannot be attached from another (different than OpenStack instance) AZ as well as network agents cannot spawn networks/ports and, more importantly, L3 Router from another AZ.

Hi,

I can confirm that this fix is only a third of the story because AZ support for networking and volumes is missing.

**Comment by mandre** [comment]
Please help us understand the issue you're facing with the current implementation.

Mismatch between the nova and cinder availability zones is an infrastructure problem and can be bypassed (as a day 2 operation) by setting the [ignore-volume-az](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#block-storage) setting to true in your cloud provider configuration.

**Comment by promiteyka** [comment]
Hello Guys.
I agree with the previous comment because only implementing availability zone support for machines doesn't solve the core issue. In real OpenStack installations, the availability zone split performed to guarantee the availability of infrastructure, which, as you have known, consists not only from virtual machine instances on the cloud but also from Cinder volumes and Neutron objects such as tenant networks and routers. It is a common mistake to ignore the whole infrastructure because of devstack-syndrome. In my opinion, this small part is unusable if you think more deeply.

**Comment by ITD27M01** [comment]
> Mismatch between the nova and cinder availability zones is an infrastructure problem and can be bypassed (as a day 2 operation) by setting the ignore-volume-az setting to true in your cloud provider configuration.

Hi,

The issue not in the mismatch but in exact value. In the provided implementation there is no any AZ configured for infrastructure things such as Networks, Routers and Volumes. By default the Neutron scheduler (and all other schedulers) will select network agents for network and router randomly which most likely will not fall into the same availability zone as provisioned instances [1]. 

One caveat about "boot from volume" nova-workflow which is used in current kubernetes openstack cloud provider code. There is no option to define availability zone for the boot_from_volume [2] and current workaround is to use the "availability zone types" [3]

[1] https://www.terraform.io/docs/providers/openstack/r/networking_network_v2.html#availability_zone_hints
[2] https://github.com/gophercloud/gophercloud/issues/1965
[3] https://docs.openstack.org/cinder/rocky/admin/blockstorage-availability-zone-type.html

**Comment by ITD27M01** [comment]
@mandre 
To understand it correctly - there can be one cinder volume type but on different availability zones. As a result, to create correct placed volume I need to specify not only volume type, but availability zone also:

```
usage: openstack volume create [-h] [-f {json,shell,table,value,yaml}]
                               [-c COLUMN] [--noindent] [--prefix PREFIX]
                               [--max-width <integer>] [--fit-width]
                               [--print-empty] [--size <size>]
                               [--type <volume-type>]
                               [--image <image> | --snapshot <snapshot> | --source <volume>]
                               [--description <description>]
                               [--availability-zone <availability-zone>]
                               [--consistency-group consistency-group>]
                               [--property <key=value>] [--hint <key=value>]
                               [--bootable | --non-bootable]
                               [--read-only | --read-write]
                               <name>
```
